# Generated by Django 5.0.1 on 2026-02-17 02:39

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "source_type",
                    models.CharField(
                        choices=[("Internal", "Internal"), ("GitHub-Linked", "GitHub-Linked")],
                        default="Internal",
                        max_length=20,
                        verbose_name="source type",
                    ),
                ),
                ("forks_count", models.IntegerField(default=0, verbose_name="forks count")),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="deleted at")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "derived_from_resource",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="forks",
                        to="resources.resource",
                        verbose_name="derived from resource",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="owner",
                    ),
                ),
            ],
            options={
                "verbose_name": "resource",
                "verbose_name_plural": "resources",
                "db_table": "resources",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ResourceVersion",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "version_number",
                    models.CharField(
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Version must be in format MAJOR.MINOR.PATCH (e.g., 1.0.0)",
                                regex="^\\d+\\.\\d+\\.\\d+$",
                            )
                        ],
                        verbose_name="version number",
                    ),
                ),
                ("title", models.CharField(db_index=True, max_length=200, verbose_name="title")),
                ("description", models.TextField(verbose_name="description")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Prompt", "Prompt"),
                            ("Workflow", "Workflow"),
                            ("Notebook", "Notebook"),
                            ("Dataset", "Dataset"),
                            ("Tool", "Tool"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                        verbose_name="type",
                    ),
                ),
                ("tags", models.JSONField(default=list, verbose_name="tags")),
                ("content", models.TextField(blank=True, null=True, verbose_name="content")),
                ("content_hash", models.CharField(blank=True, max_length=64, null=True, verbose_name="content hash")),
                ("repo_url", models.URLField(blank=True, max_length=500, null=True, verbose_name="repository URL")),
                ("repo_tag", models.CharField(blank=True, max_length=100, null=True, verbose_name="repository tag")),
                ("repo_commit_sha", models.CharField(blank=True, max_length=40, null=True, verbose_name="commit SHA")),
                ("license", models.CharField(blank=True, max_length=50, null=True, verbose_name="license")),
                ("example", models.TextField(blank=True, null=True, verbose_name="example")),
                ("changelog", models.TextField(blank=True, null=True, verbose_name="changelog")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Sandbox", "Sandbox"),
                            ("Pending Validation", "Pending Validation"),
                            ("Validated", "Validated"),
                        ],
                        db_index=True,
                        default="Sandbox",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "validated_at",
                    models.DateTimeField(blank=True, db_index=True, null=True, verbose_name="validated at"),
                ),
                ("is_latest", models.BooleanField(db_index=True, default=True, verbose_name="is latest")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="resources.resource",
                        verbose_name="resource",
                    ),
                ),
            ],
            options={
                "verbose_name": "resource version",
                "verbose_name_plural": "resource versions",
                "db_table": "resource_versions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="resource",
            name="derived_from_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="derived_resources",
                to="resources.resourceversion",
                verbose_name="derived from version",
            ),
        ),
        migrations.AddIndex(
            model_name="resourceversion",
            index=models.Index(fields=["resource", "-created_at"], name="resource_ve_resourc_f1c51a_idx"),
        ),
        migrations.AddIndex(
            model_name="resourceversion",
            index=models.Index(fields=["resource", "is_latest"], name="resource_ve_resourc_9d3b65_idx"),
        ),
        migrations.AddIndex(
            model_name="resourceversion",
            index=models.Index(fields=["status"], name="resource_ve_status_6f0c9b_idx"),
        ),
        migrations.AddIndex(
            model_name="resourceversion",
            index=models.Index(fields=["-validated_at"], name="resource_ve_validat_3c802c_idx"),
        ),
        migrations.AddIndex(
            model_name="resourceversion",
            index=models.Index(fields=["-created_at"], name="resource_ve_created_5bb1ff_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="resourceversion",
            unique_together={("resource", "version_number")},
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(fields=["owner", "-created_at"], name="resources_owner_i_9a57e7_idx"),
        ),
        migrations.AddIndex(
            model_name="resource",
            index=models.Index(fields=["-created_at"], name="resources_created_b3da52_idx"),
        ),
    ]
