# Generated by Django 5.0.1 on 2026-02-17 02:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resourceversion",
            name="tags",
            field=models.JSONField(blank=True, default=list, verbose_name="tags"),
        ),
    ]
